name: explore-jaeb
channels:
  - defaults
  - conda-forge
dependencies:
  - pip==20.0.2
  - python=3.7.3
  - pip:
    - -r file:requirements.txt
    - orjson==3.1.2
    - pyarrow==0.17.1
    - ipython==7.16.1
    - git+git://github.com/tidepool-org/data-science-models
    - git+git://github.com/tidepool-org/loop-issue-report@rpw/initial
    - pyloopkit-test
